### ISSUE TITLE
hi , how can I install this script on a mac computer ?

### ISSUE THREAD

**Issue by Pancho111** [RobRoyce/gdax_logger#1]
HI , 
I have been looking for a script like this , how can I intall this on my macbook pro computer.
I have python 2.7 , it is giving me an error .
thanks

**Comment by RobRoyce** [comment]
Hi, thank you for the feedback.
Would you mind replying with the error you're receiving?
I did forget to mention that this script depends on the Anaconda3 library which contains various packages that I'm using here. If you don't have Anaconda installed, please check [here](https://www.anaconda.com/download/#macos)

**Comment by Pancho111** [comment]
Hi , 
thank you for your reply 
this is the error I am getting 

Last login: Mon Feb  5 22:02:06 on ttys000
calixtos-MacBook-Pro:~ pancho$ cd /Users/pancho/gdax_logger-master 
calixtos-MacBook-Pro:gdax_logger-master pancho$ python /Users/pancho/gdax_logger-master/gdax_ticker_logger.py 
Traceback (most recent call last):
  File "/Users/pancho/gdax_logger-master/gdax_ticker_logger.py", line 14, in <module>
    from GDAXTickerLogger import GDAXTickerLogger
  File "/Users/pancho/gdax_logger-master/GDAXTickerLogger.py", line 1, in <module>
    from GDAXLoggerBase import GDAXLoggerBase
  File "/Users/pancho/gdax_logger-master/GDAXLoggerBase.py", line 2, in <module>
    from queue import Queue
ImportError: No module named queue
calixtos-MacBook-Pro:gdax_logger-master pancho$ 

Thanks

**Comment by RobRoyce** [comment]
[See here](https://docs.python.org/2/library/queue.html)

> The Queue module has been renamed to queue in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3.

I would *highly* recommend using Python 3. If for some reason you must use Python 2, you can try changing `queue` to `Queue` in GDAXLoggerBase.py.

**Comment by Pancho111** [comment]
Thank you very much for your help 
I am using python2  so like you said I changed queue to Queue and now I am getting this

Last login: Thu Feb  8 08:22:18 on ttys000
calixtos-MacBook-Pro:~ Pancho$ python2 /Users/Pancho/gdax_logger-master/gdax_ticker_logger.py 
Exception AttributeError: "'GDAXTickerLogger' object has no attribute '_logger_thread'" in <bound method GDAXTickerLogger.__del__ of <GDAXTickerLogger.GDAXTickerLogger object at 0x10127fa90>> ignored
calixtos-MacBook-Pro:~ Pancho$ 


Thanks
